### ISSUE TITLE
not provide support to debian 9.9

### ISSUE THREAD

**Issue by empereira** [gabe-sky/puppet-ansible#1]
Hello @gabe-sky ,

I installed your plugin, but at the beginning it is not compatible with debian 9.9?

I changed the $ bail_on_debians option to false, but the error below occurred.
```
Empty String provided for package name (file: /etc/puppetlabs/code/environments/production/modules/ansible/manifests/controller.pp, line: 33, column: 3)
```

**Comment by gabe-sky** [comment]
What you'll need to do is determine which packages are required for Debian 9, and update params.pp to have a $controller_pkglist setting for Debian 9, similar to how I've done RedHat 6 and 7.  Copy and paste one of those with '9' inside the debian block.

Send over a pull request and I'll add it.
